backend:
  name: git-gateway
  branch: main # Change to 'master' if your GitHub branch is named master

media_folder: "assets/images"
public_folder: "/assets/images"

site_url: https://rockyhouseofessentials.netlify.app
display_url: https://rockyhouseofessentials.netlify.app

collections:
  - name: "products"
    label: "Suits & Items"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Product Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
