backend:
  name: git-gateway
  branch: main # If your GitHub says 'master', change this to master

media_folder: "assets/images"
public_folder: "/assets/images"

site_url: https://rockyhouseofessentials.netlify.app

collections:
  - name: "products"
    label: "Inventory"
    folder: "data/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Item Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Upload Photo/Video", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
